### PR TITLE
Nix Flakes

### PR DESCRIPTION
**Pull request by cab404**
This adds required files for nix support, and some documentation to README.md on how to use them.

It should be compatible with x86_64-linux, aarch64-linux and x86_64-darwin platforms.
All built binaries are working.
Built Nix package also contains udev rules, so if you install it in NixOS, it will apply rules automagically.

### CODE REVIEW

**Comment by gsurkov** [comment]
FIrst and foremost, thank you for your input!

As there is no proper package managers support yet, may I ask you to do the following as well:
1. Create a separate directory called `packages/nix` or something like that
2. Create a general `packages/README.md` and a nix-related `packages/nix/README.md`
3. Put all nix-related files into the `packages/nix` directory
4. Make the necessary links from the main `README.md`, removing all specific information from it

This  configuration would allow for easier integration with other package management systems later.

NB: You might also want to disable the automatic update feature via `DISABLE_APPLICATION_UPDATES` as it doesn't really make sense to have it enabled in a system package.

**Comment by cab404** [comment]
Can I call the directory "contrib" instead of "packages" though? This is a standard for contributions, and is present in many other open-source projects.
> NB: You might also want to disable the automatic update feature via DISABLE_APPLICATION_UPDATES as it doesn't really make sense to have it enabled in a system package.

Thank you, that's something I was searching for :heart:

**Comment by gsurkov** [comment]
>Can I call the directory "contrib" instead of "packages" though?

Yep, that sounds about right.

**Comment by cab404** [comment]
@gsurkov I've applied your suggestions to current packaging, and expanded documentation.

**Comment by cab404** [comment]
I can also add Nix CI job, if you want

**Comment by gsurkov** [comment]
This is OK as it is, thanks.

**Pull request merged**
